### ISSUE TITLE
Global Command-Line Options

### ISSUE THREAD

**Issue by cartermak** [NASA-AMMOS/aerie-cli#36]
Ticket to investigate whether Typer gives us a way to define a command-line arg that applies to all commands in an app. Possible use cases:

- Pass the Hasura admin secret on an ad-hoc basis (#22)
- Pass an ad-hoc host name and/or configuration instead of using persistent sessions (#14)
- Specify output options (verbosity, pretty-print vs. script-friendly responses, etc.)

**Comment by Navarro-Jonathan** [comment]
One solution is to use typer's app.callback, which allows us to receive additional command-line args. We can use this to write the arguments to a global variable.

Typer also provides a context that can be supplied to methods, but that would require passing the context to every command to work globally.

One issue with the current method is that the additional options can only be passed after aerie-cli. The options cannot come after commands. For example, ```aerie-cli --v plans list``` will be accepted. However, ```aerie-cli plans list --v``` will be rejected. This can be written in the documentation in order to avoid any confusion.

For an example of this solution in practice, see: 6216bb5
